//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFUpscalerHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720x540")]
        public string dimension_png {
            get {
                return ((string)(this["dimension_png"]));
            }
            set {
                this["dimension_png"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotSet")]
        public string ffmpeg_location {
            get {
                return ((string)(this["ffmpeg_location"]));
            }
            set {
                this["ffmpeg_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool open_folder {
            get {
                return ((bool)(this["open_folder"]));
            }
            set {
                this["open_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedPreset {
            get {
                return ((int)(this["selectedPreset"]));
            }
            set {
                this["selectedPreset"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-r 24000/1001 -f image2 -start_number 1 -i [InputImgLocation]\%06d.png -c:v libx264 -preset veryslow -crf 18 -pix_fmt yuv420p -profile:v high -level:v 4.1 -refs 4 -bf 3 -vf colormatrix=bt601:bt709 -color_primaries bt709 -color_trc bt709 -colorspace bt709 [OutputLocation]")]
        public string DefaultFfmpegPreset {
            get {
                return ((string)(this["DefaultFfmpegPreset"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"x264: 1080p 24fps
-r 24000/1001 -f image2 -start_number 1 -i [InputImgLocation]\%06d.png -c:v libx264 -preset veryslow -crf 18 -pix_fmt yuv420p -profile:v high -level:v 4.1 -refs 4 -bf 3 -vf colormatrix=bt601:bt709 -color_primaries bt709 -color_trc bt709 -colorspace bt709 [OutputLocation]
x264: 1080p 25fps
-r 25 -f image2 -start_number 1 -i [InputImgLocation]\%06d.png -c:v libx264 -preset veryslow -crf 18 -pix_fmt yuv420p -profile:v high -level:v 4.1 -refs 4 -bf 3 -vf colormatrix=bt601:bt709 -color_primaries bt709 -color_trc bt709 -colorspace bt709 [OutputLocation]")]
        public string presets {
            get {
                return ((string)(this["presets"]));
            }
            set {
                this["presets"] = value;
            }
        }
    }
}
